FROM node:18-alpine AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
RUN yarn global add serve
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]