FROM python:3.11-slim

WORKDIR /app

# system deps for psycopg2, GEOS (used by geo libs)
RUN apt-get update && apt-get install -y build-essential libpq-dev gcc g++ git curl \
    libgdal-dev gdal-bin && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app/app
COPY data /app/data

ENV PYTHONUNBUFFERED=1
EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]